### PR TITLE
Improve Persian translation

### PR DESCRIPTION
**Pull request by mohsenasm**
Hi,
Thanks for your great site 👍 !
I have improved the Persian translation to be more fluent.

### CODE REVIEW

**Comment by tulir** [comment]
@usefss want to review this?

**Comment by mohsenasm** [comment]
Hi again,
When do you plan to merge this?

**Comment by usefss** [comment]
> @usefss want to review this?

I can.

**Review by usefss — APPROVED** [review]
good to go!

**Pull request merged**
