### PR TITLE
bulgarian fixes

### PR DESCRIPTION
**Pull request by j4cegh**

### CODE REVIEW

**Comment by j4cegh** [comment]
I was drunk when I did these commits for real

**Review by mtatko — APPROVED** [review]
Coding while drunk might not be the best idea. I'll allow it tho

**Comment by j4cegh** [comment]
> Coding while drunk might not be the best idea. I'll allow it tho

By drunk I meant dumb as hell. Also, I'm talking about the past ones.

**Comment by mtatko** [comment]
Oh, hahaha. That's okay, it's important that the mistakes were fixed 😇

**Pull request merged**
